server:
    port: 8080
    address: localhost
    name : 测试用例
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        pool:
            max-idle: 100
            min-idle: 1
            max-active: 1000
            max-wait: -1


